# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do |lane|
  cocoapods
  increment_build_number(xcodeproj: "TestSwifUI.xcodeproj")
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :send_version_to_testflight do
    build_app(workspace: "TestSwifUI.xcworkspace", scheme: "Test", export_method:"app-store")
    upload_to_testflight
    send_message_to_discord(from:"To TestFlight")
    git_push
  end

  desc "send version to app center"
  lane :send_version_to_app_center do
    build_app(workspace: "TestSwifUI.xcworkspace", scheme: "Test", export_method:"development")
    appcenter_upload(
      api_token: "",
      owner_name: "",
      owner_type: "",
      app_name: "",
      notify_testers: true)
      send_message_to_discord(from:"TO APP CENTER")
      git_push
  end

  error do |lane, exception|
    discord_notifier(
      webhook_url:"",
      title:"❌❌" +exception.to_s+ "❌❌",
      description: exception.error_info.to_s)
end

#Private lanes
  private_lane :git_push do
    current_branch = git_branch
    puts "current branch is " + current_branch
    git_commit(path: ".", message: "commit from fastlane")
    push_to_git_remote(remote: "origin",
      local_branch: current_branch,
      remote_branch: current_branch)
  end

  private_lane :send_message_to_discord do |options|
    build_number = get_build_number(xcodeproj: "TestSwifUI.xcodeproj")
    version = get_version_number(xcodeproj: "TestSwifUI.xcodeproj", target:"Test")
    discord_notifier(
    webhook_url:"",
    title: "✅✅✅✅✅send version " + options[:from] + " number version " + version,
    description: "build number " + build_number)
  end
end
